### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by LinnHtetLwin**

### CODE REVIEW

**Comment by davidbr4gg** [comment]
Needs to be in Vue..

**Comment by Sumanyu7** [comment]
Converted to Vue while keeping the same Form and styling done by Linn.
/Feedback

**Comment by Ethanol10** [comment]
The project structure in this branch is currently old, it'd be great if you could update it to match the current project structure with the new UI.

**Comment by Sumanyu7** [comment]
Done

**Review by Ethanol10 — APPROVED** [review]
Nothing seems to infringe other parts of the dashboard, seems good to push

**Pull request merged**
